files:
 numpy: Data/npy_spect # spectrograms as ndarray in binary format
 vox_celeb_splits: Data/VoxCeleb1/iden_split_test.txt
 vox_celeb_meta: Data/VoxCeleb1/vox1_meta.csv
 vox_dev_wav: Data/VoxCeleb1/vox1_dev_wav/wav
 model_weights: Data/model_weights

spectrogram:
  sampling_rate: 16000 # kHz
  sample_length: 0.4 # sec
  offset_range: [0.1, 1.5] #sec
  fft_window: 1024 # samples
  hop_length: 160 # samples

dataset:
  split: train-dev

generator:
