input_data:
  sampling_rate: 16000
  mel_spectrogram_x: 40
  mel_spectrogram_y: 128
  batch_size: 64
  batch_shuffle: True
  channels: 1 # 1 = mono, 2 = stereo

topology:
  blstm1_units: 128

  dropout1: 0.5

  blstm2_units: 128

  dense1_units: 400 # timit setting: 10 * 40 speakers

  dropout2: 0.25

  dense2_units: 200 # timit setting: 5 * 40 speakers

  dense3_units: 40 # timit setting: 40 speakers


  optimizer:
    type: adam
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 1e-08
    decay: 0.0

  output_layer: layer8